### ISSUE TITLE
impData.dart file is missing

### ISSUE THREAD

**Issue by digitpk** [harshkumarkhatri/Booking-App-Event-Creator#69]
how can i create the file or what data its holds for successfully build of the application as the impData.dart file is missing from utils folder.

**Comment by harshkumarkhatri** [comment]
So as you mentioned impData.dart file is present in utils. I have added the content for the file. You can create your apis and fcm key and add them to it for the functioning of the app.
`// Holds the data which should be private and should not be shared with the masses

class impData {
  String sendUpdateAboutEventUpdated =
      "";
  String whatsNewAPIURL =
      "";
  String fcmKey =
      "";
}
`

sendUpdateAboutEventUpdated is an API that will be sending a mail to the user as soon as the event is updated [POST API]
whatsNewAPIURL is an API for displaying data from the API related to all the new features which have been added in the app. [GET API]
fcmKey is the firebase cloud messaging key fr sending notifications to the users.

**Comment by harshkumarkhatri** [comment]
Do let me know if you need any more help else do close the issue if I was able to resolve your query.

**Comment by digitpk** [comment]
I am a beginner for this project can you guide me on how can I make the APIs for the three events. Maybe you can use dummy links in them so that I may know how to create them and replace them with mine after creating them.

**Comment by harshkumarkhatri** [comment]
Hey @digitpk It is a bit difficult to explain the things over here and also the APIs I created were on a chargeable mode. If you are further interested in creating the API and you are fine paying for the things, I would be more than happy to assist you with the process.

**Comment by digitpk** [comment]
Let's discuss via email: digitpakistan@outlook.com
